### ISSUE TITLE
Rss feed doesn't seem to be updating

### ISSUE THREAD

**Issue by Balentay** [conoro/tiktok-rss-flat#13]
I noticed that despite the flat workflow triggering it isn't populating my rss folder.  When I tried out one of the rss feeds you already have set up I also noticed that the feed was a few tiktoks behind- including one iamtabithabrown had uploaded 2 hours ago

**Comment by conoro** [comment]
It looks like TikTok has broken the library this tool relies on, yet again. It's really a game of whack-a-mole by the library author, as TikTok constantly change things (presumably to prevent bots etc). Generally what happens is that a library fix is made and we'll automatically get it on the next run of this tool. 

TBH, I wouldn't rely on tiktok-rss-flat - we really need TikTok to provide a proper API or actual RSS feeds.
