### ISSUE TITLE
Is this project still working with TikTokApi V5?

### ISSUE THREAD

**Issue by DrLai12club** [conoro/tiktok-rss-flat#18]
I notice that after the discussion at https://github.com/conoro/tiktok-rss-flat/issues/14, you update this project for TikTokApi v5, but it seems not work (like https://github.com/conoro/tiktok-rss-flat/runs/5983470304?check_suite_focus=true).

Are you just trying to fix it but not success?

**Comment by conoro** [comment]
But it appears that the API call I'm using does not work in V5. See https://github.com/davidteather/TikTok-Api/issues/838

**Comment by conoro** [comment]
Working again.
