### ISSUE TITLE
Not running?

### ISSUE THREAD

**Issue by Glench** [conoro/tiktok-rss-flat#2]
Hi! I forked this repo and modified everything as described in the instructions but Github doesn't seem to be running the workflow. Are you able to look at it quickly to see if anything is wrong? https://github.com/Glench/tiktok-rss-flat

**Comment by conoro** [comment]
@Glench   I can't see anything obviously wrong with your setup. Do you see a "run workflow" option at the top of https://github.com/Glench/tiktok-rss-flat/actions/workflows/flat.yml  ?

![Screenshot 2021-08-05 at 15 16 09](https://user-images.githubusercontent.com/586566/128365700-5ff56f89-5813-4891-a8d7-7bd3822c25a6.png)

**Comment by Glench** [comment]
Ah, Github automatically disables workflows in forked repos. I had to enable the workflow (with two separate screens) when visiting the file you linked to, but it seems to be working now! Thank you!

**Comment by conoro** [comment]
Ah good to know! Glad it's working now.

**Comment by Glench** [comment]
Hm actually it's running successfully according to Github actions but no data seems to be added to the RSS folder...

**Comment by conoro** [comment]
@Glench The latest version of the TikTok library changed some of the function names. I've pushed a tiny change to my repo to reflect the change (just change line 23 of postprocessing.py to `tiktoks = api.by_username(user, count=count)`)

Seems to be working again now.

**Comment by Glench** [comment]
It works! Thank you!

**Comment by amblerkr** [comment]
same here. The rss folder isn't updating. Help me.
