### ISSUE TITLE
post fetch phase uses wrong url and gives error 128 on /usr/bin/git push

### ISSUE THREAD

**Issue by ttscrape** [conoro/tiktok-rss-flat#23]
The extraction from TikTok actually works well, data is being fetched and the xml files are prebuilt in memory, only during the post fetch data phase I get an error from get (128).

It tries to go to the github.com url instead of the subdomain.github.io one. The url configured in ghPagesURL / postprocessing.py doesn't seem to be used. Any advice?

 /usr/bin/git push
  remote: Permission to xxx/tiktok-rss.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/xxx/tiktok-rss/': The requested URL returned error: 403
  Error: Post script failed! The process '/usr/bin/git' failed with exit code 128

**Comment by conoro** [comment]
@ttscrape It might be a permissions issue. Check the repo Settings > GitHub Actions > General > Workflow Permissions. Make sure it's set to Read & Write permissions.

**Comment by ttscrape** [comment]
That did the trick. Thanks for the help @conoro
