### ISSUE TITLE
The RSS folder does not create new and returns an error.

### ISSUE THREAD

**Issue by amblerkr** [conoro/tiktok-rss-flat#3]
> The page build completed successfully, but returned the following warning for the `main` branch:
> 
> The CNAME `tiktokrss.conoroneill.com` is already taken. Check out https://docs.github.com/articles/troubleshooting-custom-domains#cname-errors for more information.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://docs.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request at https://support.github.com/contact?repo_id=398568195&page_build_id=274193942 

I've used GitHub action a few times. Allow users to create and operate specific branches.
like `gh-pages`

**Comment by conoro** [comment]
Deleting the CNAME file should take care of that error. It's specific to my setup.

I've also made a few quick fixes and it seems to be generating the RSS files again.
