### ISSUE TITLE
No entries on rss directory

### ISSUE THREAD

**Issue by hel1o-gomes** [conoro/tiktok-rss-flat#35]
It's running OK but I have no entries in my RSS directory. Does it create new XMLs only when a new video is posted?  My repo is public if you want to check.

**Comment by conoro** [comment]
@hel1o-gomes  You need to enable the "flat" GitHub Action. If you go here, you can see it's disabled and has never run. 

https://github.com/hel1o-gomes/tiktok-rss-flat/actions
