### ISSUE TITLE
Worked for a bit, stopped working

### ISSUE THREAD

**Issue by pukku** [conoro/tiktok-rss-flat#4]
Hi! First, many thanks for creating this! I was able to get the RSS feeds I was interested in, which is great!

Sadly, though, about four days ago it seems to have stopped working? I don't have anything new since Sept 13th, even though I've verified that new videos have been posted.

It also looks like the problem is affecting your version of the repository as well?

Although I understand some of what is happening, I'm afraid I don't know enough to debug the issue. Do you have any suggestions?

Thanks,
Ricky

**Comment by conoro** [comment]
@pukku Thanks for the report. Unfortunately the problem is in the TikTok-Api library that does all the hard work here. The author is aware of it and is working on it. See https://github.com/davidteather/TikTok-Api/issues/695

I'll leave this open until the problem is solved at their end.

**Comment by conoro** [comment]
The API fix to V4.0.2 seems to have fixed things again and I'm now starting to see updated feeds.

**Comment by pukku** [comment]
Thanks! It's working for me as well...
