### ISSUE TITLE
must enable actions after forking

### ISSUE THREAD

**Issue by I-Like-Them-Apples** [conoro/tiktok-rss-flat#5]
Hey thanks for this so much, I hate getting sucked into tiktok, but there are a few creators that I'd like to follow - this would be the perfect solution. 

so I think I set it up right, but for someone that is used to getting around github, it's worth pointing out in the readme, that after forking and setting up all the variables, you mus explicitly enable actions in the actions tab after it is forked. 

Again, thanks for this - I can't wait for the tiktok api to get fixed so I can properly test this out.

**Comment by conoro** [comment]
Thanks! Added to instructions. Fingers crossed on the API!
