### ISSUE TITLE
some tiktok accounts dosnt work but some works i think its a bug btw

### ISSUE THREAD

**Issue by candyily** [conoro/tiktok-rss-flat#9]
i tried so many times but looks like some tiktok account wont get data:
it stop working for got7official for example:
![image](https://user-images.githubusercontent.com/76725161/141665893-e15907a3-dbfc-4a1c-b1ea-143f6e0d944d.png)

**Comment by conoro** [comment]
@candyily Unfortunately the underlying library that I use is being blocked again by TikTok via Captcha. I believe some work is being done on trying to fix it. But until then, we are all in the same situation. It is over a week since any of the accounts I follow have worked.

**Comment by pukku** [comment]
Out of curiosity, do you have an issue number or link to a ticket for the library? I'd like to see if there's a chance this will start working again, or if I should disable the repeating task...

Thanks!
Ricky

**Comment by conoro** [comment]
There is actually a PR with a fix which just needs to be merged by the author. 

Issue: https://github.com/davidteather/TikTok-Api/issues/750 
PR: https://github.com/davidteather/TikTok-Api/pull/753

**Comment by pukku** [comment]
Thanks! I'll follow that to see if this will get fixed...

**Comment by k3ns1n** [comment]
Try this https://ttrss.mybluemix.net
It use mobile api

**Comment by BeatRoy** [comment]
@k3ns1n Is there any source code of this project?
